import Head from "next/head";
import { useState } from "react";
import PlateForm from "~/components/Forms/PlateForm";
import FineTableItem from "~/components/Table/FineTableItem";
import Table from "~/components/Table/Table";
import type { Edpk } from "~/types/responses";

export default function Home() {
  const [fines, setFines] = useState<Edpk[]>([]);

  return (
    <>
      <Head>
        <title>QR ePPK</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-primary/20 flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            QR ePPK
          </h1>
          <div className="gap-4 sm:grid-cols-2 md:gap-8">
            <PlateForm saveFines={(data) => setFines(data)} />
          </div>
          {fines.length > 0 ? (
                <Table
                  headers={[
                    "Broj Naloga",
                    "Vreme Izdavanja",
                    "Poziv Na Broj",
                    "Za Uplatu",
                  ]}
                >
                  {fines.length > 0 &&
                    fines.map((fine, index) => (
                      <FineTableItem {...fine} key={`fine-${index}`} />
                    ))}
                </Table>
              ) : null}
          </div>
      </main>
    </>
  );
}
