import Head from "next/head";
import PlateForm from "~/components/Forms/PlateForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>QR ePPK</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-primary/20 flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            QR ePPK
          </h1>
          <div className="gap-4 sm:grid-cols-2 md:gap-8">
            <PlateForm />
          </div>
        </div>
      </main>
    </>
  );
}
